// hackathonsData.js
export const hackathons = [
    {
      id: 1,
      title: "One Trillion Agents Hackathon",
      image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      daysLeft: "6 days left",
      location: "Online",
      prize: "$115,500 in prizes",
      participants: 1866,
      date: "Jan 31 - Mar 02, 2025",
      organizer: "NEAR Protocol",
      topics: ["Blockchain", "Machine Learning/AI"],
      featured: true,
    },
    {
      id: 2,
      title: "Predictive AI In Healthcare with FHIR®",
      image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      daysLeft: "5 days left",
      location: "Online",
      prize: "$25,000 in prizes",
      participants: 2348,
      date: "Dec 18, 2024 - Mar 02, 2025",
      organizer: "Darena Solutions",
      topics: ["Health", "Machine Learning/AI"],
      featured: false,
    },
    {
      id: 3,
      title: "Azure AI Developer Hackathon",
      image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
      daysLeft: "about 1 month left",
      location: "Online",
      prize: "$10,000 in prizes",
      participants: 915,
      date: "Feb 18 - Mar 28, 2025",
      organizer: "Microsoft",
      topics: ["Cloud Computing", "AI"],
      featured: true,
    },
    {
        id: 4,
        title: "Azure AI Developer Hackathon",
        image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        daysLeft: "about 1 month left",
        location: "Online",
        prize: "$10,000 in prizes",
        participants: 915,
        date: "Feb 18 - Mar 28, 2025",
        organizer: "Microsoft",
        topics: ["Cloud Computing", "AI"],
        featured: true,
      },
      {
        id: 5,
        title: "Azure AI Developer Hackathon",
        image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        daysLeft: "about 1 month left",
        location: "Online",
        prize: "$10,000 in prizes",
        participants: 915,
        date: "Feb 18 - Mar 28, 2025",
        organizer: "Microsoft",
        topics: ["Cloud Computing", "AI"],
        featured: true,
      },
      {
        id: 6,
        title: "Azure AI Developer Hackathon",
        image: "https://th.bing.com/th/id/OIP.ms2GntF2fg76gVirekBD5AEsEs?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        daysLeft: "about 1 month left",
        location: "Online",
        prize: "$10,000 in prizes",
        participants: 915,
        date: "Feb 18 - Mar 28, 2025",
        organizer: "Microsoft",
        topics: ["Cloud Computing", "AI"],
        featured: true,
      },
  ];
  